# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.cache/wt} [current_project]
set_property parent.project_path {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo {d:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/sources_1/new/Add_Sub_unit.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/new/D_FF.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/sources_1/imports/new/Decoder_3_to_8.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/sources_1/new/FA.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/sources_1/new/HA.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/new/Instruction Decoder.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/new/LUT_16_7.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/new/Mux_2way_3bit.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/new/Mux_2way_4bit.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/sources_1/imports/new/Mux_8way_4bit.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/new/PC.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/new/PCReg.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/new/PROM.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/sources_1/new/RCAS_4.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/new/RCA_3.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/sources_1/imports/new/Reg.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/sources_1/new/Registerbank.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/imports/sources_1/imports/new/Slow_Clk.vhd}
  {D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/sources_1/new/NanoProcessor.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/constrs_1/imports/NanoProcessor/Basys3Labs.xdc}}
set_property used_in_implementation false [get_files {{D:/CSE S2/New folder/NanoProcessor/NanoProcessor_210190R_210242F/NanoProcessor.srcs/constrs_1/imports/NanoProcessor/Basys3Labs.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top NanoProcessor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NanoProcessor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NanoProcessor_utilization_synth.rpt -pb NanoProcessor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
